# Generated by Django 5.0.6 on 2024-05-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(default='', max_length=13, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=20)),
                ('auction_listing', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
