# Generated by Django 5.0.6 on 2024-05-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='auction_listing',
        ),
    ]
